// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2bTJsGY9iHkP6u1z_t-izd6k6eGiTdxY',
    appId: '1:333037019594:web:c763e19126c84dcf362f33',
    messagingSenderId: '333037019594',
    projectId: 'whatsapp-c19b1',
    authDomain: 'whatsapp-c19b1.firebaseapp.com',
    storageBucket: 'whatsapp-c19b1.appspot.com',
    measurementId: 'G-XEPPPHWCSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAz1AbLMXz14g0VNzJ58zqCFkTqGQYyc6Q',
    appId: '1:333037019594:android:003b81d5b296e574362f33',
    messagingSenderId: '333037019594',
    projectId: 'whatsapp-c19b1',
    storageBucket: 'whatsapp-c19b1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJCdde4cMra81IWfSNGmAOxx0Dryj2CXY',
    appId: '1:333037019594:ios:106f252444892f4a362f33',
    messagingSenderId: '333037019594',
    projectId: 'whatsapp-c19b1',
    storageBucket: 'whatsapp-c19b1.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJCdde4cMra81IWfSNGmAOxx0Dryj2CXY',
    appId: '1:333037019594:ios:106f252444892f4a362f33',
    messagingSenderId: '333037019594',
    projectId: 'whatsapp-c19b1',
    storageBucket: 'whatsapp-c19b1.appspot.com',
    iosBundleId: 'com.example.whatsapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA2bTJsGY9iHkP6u1z_t-izd6k6eGiTdxY',
    appId: '1:333037019594:web:00ec47da2aaed6c5362f33',
    messagingSenderId: '333037019594',
    projectId: 'whatsapp-c19b1',
    authDomain: 'whatsapp-c19b1.firebaseapp.com',
    storageBucket: 'whatsapp-c19b1.appspot.com',
    measurementId: 'G-NBB3C179VS',
  );
}
